// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `account_auth_to_dto`, `account_session_to_dto`, `active_timer_to_dto`, `billing_state_to_dto`, `calendar_occurrence_to_dto`, `client_result`, `completed_timer_to_dto`, `count_to_i32`, `home_task_to_dto`, `instant_to_datetime`, `json_string`, `list_to_dto`, `millis_to_datetime`, `organization_safety_to_dto`, `parse_active_timer`, `parse_completed_timer`, `parse_status`, `parse_task_due`, `parse_timer_finish_kind`, `parse_timer_mode`, `parse_timer_phase`, `parse_timer_run_state`, `parse_uuid`, `realtime_ticket_to_dto`, `reminder_to_dto`, `saturating_i32`, `schedule_to_dto`, `settlement_to_dto`, `status_to_string`, `streak_to_dto`, `sync_status_to_dto`, `task_due_to_dto`, `task_to_dto`, `task_undo_to_dto`, `template_node_to_dto`, `template_to_dto`, `timer_finish_kind_to_dto`, `timer_mode_to_dto`, `timer_phase_to_dto`, `timer_run_state_to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiGreet(name: name);

Future<String> getLocalTimeZone() =>
    RustLib.instance.api.crateApiGetLocalTimeZone();

Future<String> createDraftTask({required String title}) =>
    RustLib.instance.api.crateApiCreateDraftTask(title: title);

/// Initializes Taskveil core for the process using `db_dir`.
///
/// This creates or loads a platform Device Key, derives the SQLCipher key,
/// initializes `<db_dir>/taskveil.db`, and stores the process-global client
/// profile. Reinitializing with the same DB path succeeds idempotently;
/// reinitializing with a different DB path returns an error.
Future<void> initCore({
  required String dbDir,
  required String defaultInboxName,
}) => RustLib.instance.api.crateApiInitCore(
  dbDir: dbDir,
  defaultInboxName: defaultInboxName,
);

/// Rotates the local Device Key and SQLCipher key using the crash-recovery
/// capsule protocol. No key material crosses the Flutter bridge.
Future<PlatformInt64> rotateDeviceKey() =>
    RustLib.instance.api.crateApiRotateDeviceKey();

Future<String> getSyncServerUrl() =>
    RustLib.instance.api.crateApiGetSyncServerUrl();

Future<void> setSyncServerUrl({required String serverUrl}) =>
    RustLib.instance.api.crateApiSetSyncServerUrl(serverUrl: serverUrl);

Future<AccountSessionStateDto> getAccountSessionState() =>
    RustLib.instance.api.crateApiGetAccountSessionState();

Future<AccountAuthResultDto> accountRegister({
  required String email,
  required String password,
  String? serverUrl,
  String? deviceName,
}) => RustLib.instance.api.crateApiAccountRegister(
  email: email,
  password: password,
  serverUrl: serverUrl,
  deviceName: deviceName,
);

Future<AccountAuthResultDto> accountLogin({
  required String email,
  required String password,
  String? serverUrl,
  String? deviceName,
}) => RustLib.instance.api.crateApiAccountLogin(
  email: email,
  password: password,
  serverUrl: serverUrl,
  deviceName: deviceName,
);

Future<void> accountLogout() => RustLib.instance.api.crateApiAccountLogout();

Future<OrganizationSafetyStateDto> organizationSafetyNumber({
  required String tenantId,
  required String memberUserId,
}) => RustLib.instance.api.crateApiOrganizationSafetyNumber(
  tenantId: tenantId,
  memberUserId: memberUserId,
);

Future<OrganizationSafetyStateDto> confirmOrganizationSafetyNumber({
  required String tenantId,
  required String memberUserId,
  required String digest,
}) => RustLib.instance.api.crateApiConfirmOrganizationSafetyNumber(
  tenantId: tenantId,
  memberUserId: memberUserId,
  digest: digest,
);

Future<SyncStatusDto> getSyncStatus() =>
    RustLib.instance.api.crateApiGetSyncStatus();

Future<SyncStatusDto> syncNow() => RustLib.instance.api.crateApiSyncNow();

Future<SyncNowOutcomeDto> syncNowOutcome() =>
    RustLib.instance.api.crateApiSyncNowOutcome();

Future<BillingStateDto> billingBootstrap() =>
    RustLib.instance.api.crateApiBillingBootstrap();

Future<BillingStateDto> refreshBilling() =>
    RustLib.instance.api.crateApiRefreshBilling();

Future<BillingStateDto?> getCachedBilling() =>
    RustLib.instance.api.crateApiGetCachedBilling();

Future<RealtimeTicketDto> getRealtimeTicket() =>
    RustLib.instance.api.crateApiGetRealtimeTicket();

/// Creates a list using a client-owned fractional `sort_order`.
///
/// `sort_order` remains in the FRB contract for compatibility, but rank
/// generation and rebalance are owned by `TaskveilClient`.
Future<ListDto> createList({required String name, required String sortOrder}) =>
    RustLib.instance.api.crateApiCreateList(name: name, sortOrder: sortOrder);

Future<List<ListDto>> getLists() => RustLib.instance.api.crateApiGetLists();

Future<List<ListDto>> getArchivedLists() =>
    RustLib.instance.api.crateApiGetArchivedLists();

Future<List<TemplateDto>> getTemplates() =>
    RustLib.instance.api.crateApiGetTemplates();

Future<List<ScheduleDto>> getTemplateSchedules({required String templateId}) =>
    RustLib.instance.api.crateApiGetTemplateSchedules(templateId: templateId);

Future<String> validateRecurrenceRule({
  required String rrule,
  required PlatformInt64 startsAt,
  required String timeZone,
}) => RustLib.instance.api.crateApiValidateRecurrenceRule(
  rrule: rrule,
  startsAt: startsAt,
  timeZone: timeZone,
);

Future<TemplateDto> saveTaskAsTemplate({
  required String taskId,
  required String name,
  String? defaultListId,
}) => RustLib.instance.api.crateApiSaveTaskAsTemplate(
  taskId: taskId,
  name: name,
  defaultListId: defaultListId,
);

Future<TemplateDto> updateTemplate({
  required String templateId,
  required String name,
  String? defaultListId,
}) => RustLib.instance.api.crateApiUpdateTemplate(
  templateId: templateId,
  name: name,
  defaultListId: defaultListId,
);

Future<TemplateDto> replaceTemplateSnapshot({
  required String templateId,
  required String taskId,
}) => RustLib.instance.api.crateApiReplaceTemplateSnapshot(
  templateId: templateId,
  taskId: taskId,
);

Future<List<TaskDto>> instantiateTemplate({required String templateId}) =>
    RustLib.instance.api.crateApiInstantiateTemplate(templateId: templateId);

Future<ScheduleDto> createSchedule({
  required String templateId,
  required String rrule,
  required PlatformInt64 startsAt,
  required String timeZone,
}) => RustLib.instance.api.crateApiCreateSchedule(
  templateId: templateId,
  rrule: rrule,
  startsAt: startsAt,
  timeZone: timeZone,
);

Future<ScheduleDto> updateSchedule({
  required String scheduleId,
  required String rrule,
  required PlatformInt64 startsAt,
  required String timeZone,
  required bool enabled,
}) => RustLib.instance.api.crateApiUpdateSchedule(
  scheduleId: scheduleId,
  rrule: rrule,
  startsAt: startsAt,
  timeZone: timeZone,
  enabled: enabled,
);

Future<void> deleteSchedule({required String scheduleId}) =>
    RustLib.instance.api.crateApiDeleteSchedule(scheduleId: scheduleId);

Future<void> deleteTemplate({required String templateId}) =>
    RustLib.instance.api.crateApiDeleteTemplate(templateId: templateId);

Future<SettlementSummaryDto> settleDueSchedules({
  required PlatformInt64 atMs,
}) => RustLib.instance.api.crateApiSettleDueSchedules(atMs: atMs);

Future<StreakDto> getScheduleStreak({
  required String scheduleId,
  required PlatformInt64 atMs,
}) => RustLib.instance.api.crateApiGetScheduleStreak(
  scheduleId: scheduleId,
  atMs: atMs,
);

Future<ListDto> renameList({required String listId, required String name}) =>
    RustLib.instance.api.crateApiRenameList(listId: listId, name: name);

Future<ListDto> archiveList({required String listId}) =>
    RustLib.instance.api.crateApiArchiveList(listId: listId);

Future<ListDto> unarchiveList({required String listId}) =>
    RustLib.instance.api.crateApiUnarchiveList(listId: listId);

/// Creates a task at the end of its sibling group using a client-generated
/// fractional `sort_order`.
Future<TaskDto> createTask({
  required String listId,
  required String title,
  String? parentTaskId,
  TaskDueInput? due,
  String? note,
  int? priority,
  PlatformInt64? scheduledAt,
  int? estimatedMinutes,
}) => RustLib.instance.api.crateApiCreateTask(
  listId: listId,
  title: title,
  parentTaskId: parentTaskId,
  due: due,
  note: note,
  priority: priority,
  scheduledAt: scheduledAt,
  estimatedMinutes: estimatedMinutes,
);

Future<TaskDto> reorderTask({
  required String taskId,
  String? previousTaskId,
  String? nextTaskId,
}) => RustLib.instance.api.crateApiReorderTask(
  taskId: taskId,
  previousTaskId: previousTaskId,
  nextTaskId: nextTaskId,
);

Future<List<TaskDto>> getTasks({required String listId}) =>
    RustLib.instance.api.crateApiGetTasks(listId: listId);

Future<ActiveTimerSessionDto?> getActiveTimerSession() =>
    RustLib.instance.api.crateApiGetActiveTimerSession();

Future<ActiveTimerStartOutcomeDto> startActiveTimerSession({
  required ActiveTimerSessionDto session,
}) => RustLib.instance.api.crateApiStartActiveTimerSession(session: session);

Future<void> updateActiveTimerSession({
  required ActiveTimerSessionDto session,
}) => RustLib.instance.api.crateApiUpdateActiveTimerSession(session: session);

Future<DateTime> pomodoroTargetReachedAt({
  required ActiveTimerSessionDto session,
}) => RustLib.instance.api.crateApiPomodoroTargetReachedAt(session: session);

Future<bool> discardActiveTimerSession({required String expectedSessionId}) =>
    RustLib.instance.api.crateApiDiscardActiveTimerSession(
      expectedSessionId: expectedSessionId,
    );

Future<bool> finishActiveTimerSession({
  required CompletedTimerSessionDto session,
}) => RustLib.instance.api.crateApiFinishActiveTimerSession(session: session);

Future<List<CompletedTimerSessionDto>> getCompletedTimerSessions({
  required String taskId,
}) => RustLib.instance.api.crateApiGetCompletedTimerSessions(taskId: taskId);

Future<List<TaskDto>> searchTasks({required String query}) =>
    RustLib.instance.api.crateApiSearchTasks(query: query);

Future<List<HomeTaskDto>> getHomeTasks({
  required PlatformInt64 todayStartMs,
  required PlatformInt64 tomorrowStartMs,
}) => RustLib.instance.api.crateApiGetHomeTasks(
  todayStartMs: todayStartMs,
  tomorrowStartMs: tomorrowStartMs,
);

Future<List<CalendarOccurrenceDto>> getCalendarOccurrences({
  required CalendarRangeInput range,
}) => RustLib.instance.api.crateApiGetCalendarOccurrences(range: range);

Future<int> countTaskDescendants({required String taskId}) =>
    RustLib.instance.api.crateApiCountTaskDescendants(taskId: taskId);

Future<int> countTasksInList({required String listId}) =>
    RustLib.instance.api.crateApiCountTasksInList(listId: listId);

Future<TaskDto> updateTask({
  required String taskId,
  required String title,
  required String note,
  required int priority,
  TaskDueInput? due,
  PlatformInt64? scheduledAt,
  int? estimatedMinutes,
}) => RustLib.instance.api.crateApiUpdateTask(
  taskId: taskId,
  title: title,
  note: note,
  priority: priority,
  due: due,
  scheduledAt: scheduledAt,
  estimatedMinutes: estimatedMinutes,
);

Future<TaskDto> setTaskStatus({
  required String taskId,
  required String status,
  String? closedReason,
}) => RustLib.instance.api.crateApiSetTaskStatus(
  taskId: taskId,
  status: status,
  closedReason: closedReason,
);

Future<void> deleteTask({required String taskId}) =>
    RustLib.instance.api.crateApiDeleteTask(taskId: taskId);

Future<void> deleteList({required String listId}) =>
    RustLib.instance.api.crateApiDeleteList(listId: listId);

Future<TaskUndoDto?> getLatestTaskUndo() =>
    RustLib.instance.api.crateApiGetLatestTaskUndo();

Future<TaskDto> undoTaskOperation({required String undoId}) =>
    RustLib.instance.api.crateApiUndoTaskOperation(undoId: undoId);

Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiGetSetting(key: key);

Future<void> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiSetSetting(key: key, value: value);

Future<ReminderDto> createTaskReminder({
  required String taskId,
  required PlatformInt64 remindAt,
}) => RustLib.instance.api.crateApiCreateTaskReminder(
  taskId: taskId,
  remindAt: remindAt,
);

Future<ReminderDto> updateReminder({
  required String reminderId,
  required PlatformInt64 remindAt,
}) => RustLib.instance.api.crateApiUpdateReminder(
  reminderId: reminderId,
  remindAt: remindAt,
);

Future<ReminderDto> deleteReminder({required String reminderId}) =>
    RustLib.instance.api.crateApiDeleteReminder(reminderId: reminderId);

Future<List<ReminderDto>> clearTaskReminders({required String taskId}) =>
    RustLib.instance.api.crateApiClearTaskReminders(taskId: taskId);

Future<List<ReminderDto>> getTaskReminders({required String taskId}) =>
    RustLib.instance.api.crateApiGetTaskReminders(taskId: taskId);

Future<List<ReminderDto>> getTaskSubtreeReminders({required String taskId}) =>
    RustLib.instance.api.crateApiGetTaskSubtreeReminders(taskId: taskId);

Future<List<ReminderDto>> getListReminders({required String listId}) =>
    RustLib.instance.api.crateApiGetListReminders(listId: listId);

Future<List<ReminderDto>> listPendingReminders({
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiListPendingReminders(nowMs: nowMs);

Future<ReminderDto> snoozeReminder({
  required String reminderId,
  required PlatformInt64 snoozedUntil,
}) => RustLib.instance.api.crateApiSnoozeReminder(
  reminderId: reminderId,
  snoozedUntil: snoozedUntil,
);

class AccountAuthResultDto {
  final AccountSessionStateDto session;
  final String? recoveryKey;

  const AccountAuthResultDto({required this.session, this.recoveryKey});

  @override
  int get hashCode => session.hashCode ^ recoveryKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountAuthResultDto &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          recoveryKey == other.recoveryKey;
}

class AccountSessionStateDto {
  final bool loggedIn;
  final String? email;
  final String? userId;
  final String? tenantId;
  final String? deviceId;

  const AccountSessionStateDto({
    required this.loggedIn,
    this.email,
    this.userId,
    this.tenantId,
    this.deviceId,
  });

  @override
  int get hashCode =>
      loggedIn.hashCode ^
      email.hashCode ^
      userId.hashCode ^
      tenantId.hashCode ^
      deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountSessionStateDto &&
          runtimeType == other.runtimeType &&
          loggedIn == other.loggedIn &&
          email == other.email &&
          userId == other.userId &&
          tenantId == other.tenantId &&
          deviceId == other.deviceId;
}

class ActiveTimerSessionDto {
  final String sessionId;
  final String? taskId;
  final TimerModeDto mode;
  final TimerPhaseDto phase;
  final TimerRunStateDto state;
  final DateTime startedAt;
  final DateTime? lastResumedAt;
  final PlatformInt64 accumulatedActiveMs;
  final PlatformInt64? targetDurationMs;

  const ActiveTimerSessionDto({
    required this.sessionId,
    this.taskId,
    required this.mode,
    required this.phase,
    required this.state,
    required this.startedAt,
    this.lastResumedAt,
    required this.accumulatedActiveMs,
    this.targetDurationMs,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      taskId.hashCode ^
      mode.hashCode ^
      phase.hashCode ^
      state.hashCode ^
      startedAt.hashCode ^
      lastResumedAt.hashCode ^
      accumulatedActiveMs.hashCode ^
      targetDurationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveTimerSessionDto &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          taskId == other.taskId &&
          mode == other.mode &&
          phase == other.phase &&
          state == other.state &&
          startedAt == other.startedAt &&
          lastResumedAt == other.lastResumedAt &&
          accumulatedActiveMs == other.accumulatedActiveMs &&
          targetDurationMs == other.targetDurationMs;
}

enum ActiveTimerStartOutcomeDto { started, conflict }

class BillingStateDto {
  final String provider;
  final String providerAppUserId;
  final String lookupKey;
  final String status;
  final bool syncAllowed;
  final String? storeProductIdentifier;
  final PlatformInt64? expiresAt;
  final PlatformInt64? graceExpiresAt;
  final bool? willRenew;
  final String environment;
  final PlatformInt64? updatedAt;

  const BillingStateDto({
    required this.provider,
    required this.providerAppUserId,
    required this.lookupKey,
    required this.status,
    required this.syncAllowed,
    this.storeProductIdentifier,
    this.expiresAt,
    this.graceExpiresAt,
    this.willRenew,
    required this.environment,
    this.updatedAt,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      providerAppUserId.hashCode ^
      lookupKey.hashCode ^
      status.hashCode ^
      syncAllowed.hashCode ^
      storeProductIdentifier.hashCode ^
      expiresAt.hashCode ^
      graceExpiresAt.hashCode ^
      willRenew.hashCode ^
      environment.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillingStateDto &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          providerAppUserId == other.providerAppUserId &&
          lookupKey == other.lookupKey &&
          status == other.status &&
          syncAllowed == other.syncAllowed &&
          storeProductIdentifier == other.storeProductIdentifier &&
          expiresAt == other.expiresAt &&
          graceExpiresAt == other.graceExpiresAt &&
          willRenew == other.willRenew &&
          environment == other.environment &&
          updatedAt == other.updatedAt;
}

class CalendarOccurrenceDto {
  final TaskDto task;
  final String listName;
  final bool listArchived;
  final CalendarOccurrenceKindDto kind;

  const CalendarOccurrenceDto({
    required this.task,
    required this.listName,
    required this.listArchived,
    required this.kind,
  });

  @override
  int get hashCode =>
      task.hashCode ^ listName.hashCode ^ listArchived.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarOccurrenceDto &&
          runtimeType == other.runtimeType &&
          task == other.task &&
          listName == other.listName &&
          listArchived == other.listArchived &&
          kind == other.kind;
}

@freezed
sealed class CalendarOccurrenceKindDto with _$CalendarOccurrenceKindDto {
  const CalendarOccurrenceKindDto._();

  const factory CalendarOccurrenceKindDto.dateDue({required String dueOn}) =
      CalendarOccurrenceKindDto_DateDue;
  const factory CalendarOccurrenceKindDto.dateTimeDue({
    required DateTime dueAt,
    required String timeZone,
  }) = CalendarOccurrenceKindDto_DateTimeDue;
  const factory CalendarOccurrenceKindDto.scheduled({
    required DateTime scheduledAt,
  }) = CalendarOccurrenceKindDto_Scheduled;
  const factory CalendarOccurrenceKindDto.completed({
    required DateTime completedAt,
  }) = CalendarOccurrenceKindDto_Completed;
}

class CalendarRangeInput {
  final String startOn;
  final String endOn;
  final DateTime startAt;
  final DateTime endAt;

  const CalendarRangeInput({
    required this.startOn,
    required this.endOn,
    required this.startAt,
    required this.endAt,
  });

  @override
  int get hashCode =>
      startOn.hashCode ^ endOn.hashCode ^ startAt.hashCode ^ endAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarRangeInput &&
          runtimeType == other.runtimeType &&
          startOn == other.startOn &&
          endOn == other.endOn &&
          startAt == other.startAt &&
          endAt == other.endAt;
}

class CompletedTimerSessionDto {
  final String id;
  final String taskId;
  final TimerModeDto mode;
  final TimerFinishKindDto finishKind;
  final DateTime startedAt;
  final DateTime endedAt;
  final PlatformInt64 activeDurationMs;
  final DateTime createdAt;

  const CompletedTimerSessionDto({
    required this.id,
    required this.taskId,
    required this.mode,
    required this.finishKind,
    required this.startedAt,
    required this.endedAt,
    required this.activeDurationMs,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      taskId.hashCode ^
      mode.hashCode ^
      finishKind.hashCode ^
      startedAt.hashCode ^
      endedAt.hashCode ^
      activeDurationMs.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompletedTimerSessionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          taskId == other.taskId &&
          mode == other.mode &&
          finishKind == other.finishKind &&
          startedAt == other.startedAt &&
          endedAt == other.endedAt &&
          activeDurationMs == other.activeDurationMs &&
          createdAt == other.createdAt;
}

class HomeTaskDto {
  final TaskDto task;
  final String listName;
  final bool isHomeTarget;

  const HomeTaskDto({
    required this.task,
    required this.listName,
    required this.isHomeTarget,
  });

  @override
  int get hashCode => task.hashCode ^ listName.hashCode ^ isHomeTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeTaskDto &&
          runtimeType == other.runtimeType &&
          task == other.task &&
          listName == other.listName &&
          isHomeTarget == other.isHomeTarget;
}

class ListDto {
  final String id;
  final String name;
  final String color;
  final String icon;
  final String sortOrder;
  final bool isDefault;
  final PlatformInt64? archivedAt;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const ListDto({
    required this.id,
    required this.name,
    required this.color,
    required this.icon,
    required this.sortOrder,
    required this.isDefault,
    this.archivedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      color.hashCode ^
      icon.hashCode ^
      sortOrder.hashCode ^
      isDefault.hashCode ^
      archivedAt.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          color == other.color &&
          icon == other.icon &&
          sortOrder == other.sortOrder &&
          isDefault == other.isDefault &&
          archivedAt == other.archivedAt &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class OrganizationSafetyStateDto {
  final String ownerUserId;
  final String memberUserId;
  final String digest;
  final String decimal;
  final String qrPayload;
  final String verificationState;
  final bool ownerConfirmed;
  final bool memberConfirmed;

  const OrganizationSafetyStateDto({
    required this.ownerUserId,
    required this.memberUserId,
    required this.digest,
    required this.decimal,
    required this.qrPayload,
    required this.verificationState,
    required this.ownerConfirmed,
    required this.memberConfirmed,
  });

  @override
  int get hashCode =>
      ownerUserId.hashCode ^
      memberUserId.hashCode ^
      digest.hashCode ^
      decimal.hashCode ^
      qrPayload.hashCode ^
      verificationState.hashCode ^
      ownerConfirmed.hashCode ^
      memberConfirmed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrganizationSafetyStateDto &&
          runtimeType == other.runtimeType &&
          ownerUserId == other.ownerUserId &&
          memberUserId == other.memberUserId &&
          digest == other.digest &&
          decimal == other.decimal &&
          qrPayload == other.qrPayload &&
          verificationState == other.verificationState &&
          ownerConfirmed == other.ownerConfirmed &&
          memberConfirmed == other.memberConfirmed;
}

class RealtimeTicketDto {
  final String websocketUrl;
  final String ticket;
  final DateTime expiresAt;

  const RealtimeTicketDto({
    required this.websocketUrl,
    required this.ticket,
    required this.expiresAt,
  });

  @override
  int get hashCode =>
      websocketUrl.hashCode ^ ticket.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RealtimeTicketDto &&
          runtimeType == other.runtimeType &&
          websocketUrl == other.websocketUrl &&
          ticket == other.ticket &&
          expiresAt == other.expiresAt;
}

class ReminderDto {
  final String id;
  final String taskId;
  final PlatformInt64 remindAt;
  final PlatformInt64? snoozedUntil;
  final PlatformInt64 createdAt;

  const ReminderDto({
    required this.id,
    required this.taskId,
    required this.remindAt,
    this.snoozedUntil,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      taskId.hashCode ^
      remindAt.hashCode ^
      snoozedUntil.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReminderDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          taskId == other.taskId &&
          remindAt == other.remindAt &&
          snoozedUntil == other.snoozedUntil &&
          createdAt == other.createdAt;
}

class ScheduleDto {
  final String id;
  final String templateId;
  final String rrule;
  final PlatformInt64 startsAt;
  final String timeZone;
  final PlatformInt64? nextRunAt;
  final bool enabled;
  final String configRevision;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const ScheduleDto({
    required this.id,
    required this.templateId,
    required this.rrule,
    required this.startsAt,
    required this.timeZone,
    this.nextRunAt,
    required this.enabled,
    required this.configRevision,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      templateId.hashCode ^
      rrule.hashCode ^
      startsAt.hashCode ^
      timeZone.hashCode ^
      nextRunAt.hashCode ^
      enabled.hashCode ^
      configRevision.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScheduleDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          templateId == other.templateId &&
          rrule == other.rrule &&
          startsAt == other.startsAt &&
          timeZone == other.timeZone &&
          nextRunAt == other.nextRunAt &&
          enabled == other.enabled &&
          configRevision == other.configRevision &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class SettlementSummaryDto {
  final int generatedOccurrences;
  final int generatedTasks;
  final bool hasMore;
  final bool outboxChanged;

  const SettlementSummaryDto({
    required this.generatedOccurrences,
    required this.generatedTasks,
    required this.hasMore,
    required this.outboxChanged,
  });

  @override
  int get hashCode =>
      generatedOccurrences.hashCode ^
      generatedTasks.hashCode ^
      hasMore.hashCode ^
      outboxChanged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettlementSummaryDto &&
          runtimeType == other.runtimeType &&
          generatedOccurrences == other.generatedOccurrences &&
          generatedTasks == other.generatedTasks &&
          hasMore == other.hasMore &&
          outboxChanged == other.outboxChanged;
}

class StreakDto {
  final int current;
  final bool finalized;

  const StreakDto({required this.current, required this.finalized});

  @override
  int get hashCode => current.hashCode ^ finalized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreakDto &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          finalized == other.finalized;
}

@freezed
sealed class SyncNowOutcomeDto with _$SyncNowOutcomeDto {
  const SyncNowOutcomeDto._();

  const factory SyncNowOutcomeDto.synced({required SyncStatusDto status}) =
      SyncNowOutcomeDto_Synced;
  const factory SyncNowOutcomeDto.billingRequired() =
      SyncNowOutcomeDto_BillingRequired;
}

class SyncStatusDto {
  final bool loggedIn;
  final bool running;
  final PlatformInt64? lastSuccessAt;
  final PlatformInt64? lastFailureAt;
  final String? lastError;
  final int pushedCount;
  final int pushAckedCount;
  final int pushSupersededCount;
  final int pulledCount;
  final int appliedCount;
  final int deletedCount;
  final int decryptFailedCount;
  final int repushCount;
  final int missingKeyQuarantinedCount;
  final int corruptionQuarantinedCount;
  final int resolvedQuarantineCount;
  final bool upgradeRequired;

  const SyncStatusDto({
    required this.loggedIn,
    required this.running,
    this.lastSuccessAt,
    this.lastFailureAt,
    this.lastError,
    required this.pushedCount,
    required this.pushAckedCount,
    required this.pushSupersededCount,
    required this.pulledCount,
    required this.appliedCount,
    required this.deletedCount,
    required this.decryptFailedCount,
    required this.repushCount,
    required this.missingKeyQuarantinedCount,
    required this.corruptionQuarantinedCount,
    required this.resolvedQuarantineCount,
    required this.upgradeRequired,
  });

  @override
  int get hashCode =>
      loggedIn.hashCode ^
      running.hashCode ^
      lastSuccessAt.hashCode ^
      lastFailureAt.hashCode ^
      lastError.hashCode ^
      pushedCount.hashCode ^
      pushAckedCount.hashCode ^
      pushSupersededCount.hashCode ^
      pulledCount.hashCode ^
      appliedCount.hashCode ^
      deletedCount.hashCode ^
      decryptFailedCount.hashCode ^
      repushCount.hashCode ^
      missingKeyQuarantinedCount.hashCode ^
      corruptionQuarantinedCount.hashCode ^
      resolvedQuarantineCount.hashCode ^
      upgradeRequired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusDto &&
          runtimeType == other.runtimeType &&
          loggedIn == other.loggedIn &&
          running == other.running &&
          lastSuccessAt == other.lastSuccessAt &&
          lastFailureAt == other.lastFailureAt &&
          lastError == other.lastError &&
          pushedCount == other.pushedCount &&
          pushAckedCount == other.pushAckedCount &&
          pushSupersededCount == other.pushSupersededCount &&
          pulledCount == other.pulledCount &&
          appliedCount == other.appliedCount &&
          deletedCount == other.deletedCount &&
          decryptFailedCount == other.decryptFailedCount &&
          repushCount == other.repushCount &&
          missingKeyQuarantinedCount == other.missingKeyQuarantinedCount &&
          corruptionQuarantinedCount == other.corruptionQuarantinedCount &&
          resolvedQuarantineCount == other.resolvedQuarantineCount &&
          upgradeRequired == other.upgradeRequired;
}

class TaskDto {
  final String id;
  final String listId;
  final String? parentTaskId;
  final String title;
  final String note;
  final String status;
  final int priority;
  final TaskDueDto? due;
  final PlatformInt64? scheduledAt;
  final int? estimatedMinutes;
  final String sortOrder;
  final PlatformInt64? completedAt;
  final String? closedReason;
  final PlatformInt64? deletedAt;
  final String? assignee;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const TaskDto({
    required this.id,
    required this.listId,
    this.parentTaskId,
    required this.title,
    required this.note,
    required this.status,
    required this.priority,
    this.due,
    this.scheduledAt,
    this.estimatedMinutes,
    required this.sortOrder,
    this.completedAt,
    this.closedReason,
    this.deletedAt,
    this.assignee,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      listId.hashCode ^
      parentTaskId.hashCode ^
      title.hashCode ^
      note.hashCode ^
      status.hashCode ^
      priority.hashCode ^
      due.hashCode ^
      scheduledAt.hashCode ^
      estimatedMinutes.hashCode ^
      sortOrder.hashCode ^
      completedAt.hashCode ^
      closedReason.hashCode ^
      deletedAt.hashCode ^
      assignee.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          listId == other.listId &&
          parentTaskId == other.parentTaskId &&
          title == other.title &&
          note == other.note &&
          status == other.status &&
          priority == other.priority &&
          due == other.due &&
          scheduledAt == other.scheduledAt &&
          estimatedMinutes == other.estimatedMinutes &&
          sortOrder == other.sortOrder &&
          completedAt == other.completedAt &&
          closedReason == other.closedReason &&
          deletedAt == other.deletedAt &&
          assignee == other.assignee &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

@freezed
sealed class TaskDueDto with _$TaskDueDto {
  const TaskDueDto._();

  const factory TaskDueDto.date({required String dueOn}) = TaskDueDto_Date;
  const factory TaskDueDto.dateTime({
    required DateTime dueAt,
    required String timeZone,
  }) = TaskDueDto_DateTime;
}

@freezed
sealed class TaskDueInput with _$TaskDueInput {
  const TaskDueInput._();

  const factory TaskDueInput.date({required String dueOn}) = TaskDueInput_Date;
  const factory TaskDueInput.dateTime({
    required DateTime dueAt,
    required String timeZone,
  }) = TaskDueInput_DateTime;
}

class TaskUndoDto {
  final String id;
  final String operationType;
  final String taskId;
  final String listId;
  final String taskTitle;
  final PlatformInt64 createdAt;

  const TaskUndoDto({
    required this.id,
    required this.operationType,
    required this.taskId,
    required this.listId,
    required this.taskTitle,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      operationType.hashCode ^
      taskId.hashCode ^
      listId.hashCode ^
      taskTitle.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskUndoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          operationType == other.operationType &&
          taskId == other.taskId &&
          listId == other.listId &&
          taskTitle == other.taskTitle &&
          createdAt == other.createdAt;
}

class TemplateDto {
  final String id;
  final String name;
  final String? defaultListId;
  final String snapshotRevision;
  final List<TemplateNodeDto> nodes;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const TemplateDto({
    required this.id,
    required this.name,
    this.defaultListId,
    required this.snapshotRevision,
    required this.nodes,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      defaultListId.hashCode ^
      snapshotRevision.hashCode ^
      nodes.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TemplateDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          defaultListId == other.defaultListId &&
          snapshotRevision == other.snapshotRevision &&
          nodes == other.nodes &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class TemplateNodeDto {
  final String nodeKey;
  final String? parentNodeKey;
  final int siblingOrder;
  final String title;
  final String note;
  final int priority;
  final int? estimatedMinutes;

  const TemplateNodeDto({
    required this.nodeKey,
    this.parentNodeKey,
    required this.siblingOrder,
    required this.title,
    required this.note,
    required this.priority,
    this.estimatedMinutes,
  });

  @override
  int get hashCode =>
      nodeKey.hashCode ^
      parentNodeKey.hashCode ^
      siblingOrder.hashCode ^
      title.hashCode ^
      note.hashCode ^
      priority.hashCode ^
      estimatedMinutes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TemplateNodeDto &&
          runtimeType == other.runtimeType &&
          nodeKey == other.nodeKey &&
          parentNodeKey == other.parentNodeKey &&
          siblingOrder == other.siblingOrder &&
          title == other.title &&
          note == other.note &&
          priority == other.priority &&
          estimatedMinutes == other.estimatedMinutes;
}

enum TimerFinishKindDto { completed, interrupted }

enum TimerModeDto { pomodoro, stopwatch }

enum TimerPhaseDto { work, shortBreak, longBreak }

enum TimerRunStateDto { running, paused }
