// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_auth`, `account_runtime_state`, `account_session_to_dto`, `active_sync_context`, `apply_pull_list`, `apply_pull_record`, `apply_pull_task`, `clear_account_settings`, `core_state`, `count_to_i32`, `dek_for_task_list`, `enqueue_list_sync`, `enqueue_merged_plaintext`, `enqueue_plaintext`, `enqueue_task_sync`, `has_active_sync_context`, `home_task_to_dto`, `list_from_plaintext`, `list_plaintext`, `list_to_dto`, `load_reorder_boundary`, `logged_out_account_state`, `now_ms`, `option_i32_value`, `option_i64_value`, `option_string_value`, `option_uuid_value`, `parse_status`, `parse_uuid`, `persist_account_state`, `record_hlc_or_initial`, `reminder_to_dto`, `replace_account_runtime_state`, `run_async`, `run_sync_now`, `status_to_string`, `store_sync_plaintext`, `stored_sync_plaintext`, `sync_runtime_state`, `sync_status_dto`, `task_from_plaintext`, `task_plaintext`, `task_to_dto`, `task_undo_operation_to_string`, `task_undo_to_dto`, `tick_local_hlc`, `usize_to_i32`, `value_bool`, `value_i64`, `value_string`, `value_uuid`, `with_list_repository`, `with_reminder_repository`, `with_settings_repository`, `with_sync_repository`, `with_task_repository`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AccountAuthMode`, `AccountRuntimeState`, `ActiveSyncContext`, `CoreState`, `LocalSyncKeys`, `SyncRuntimeState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiGreet(name: name);

Future<String> createDraftTask({required String title}) =>
    RustLib.instance.api.crateApiCreateDraftTask(title: title);

/// Initializes Todori core for the process using `db_dir`.
///
/// This creates or loads a platform Device Key, derives the SQLCipher key,
/// initializes `<db_dir>/todori.db`, and stores only the DB path plus derived
/// key in process-global state. Reinitializing with the same DB path succeeds
/// idempotently; reinitializing with a different DB path returns an error
/// because `OnceLock` cannot safely swap process-global state.
Future<void> initCore({
  required String dbDir,
  required String defaultInboxName,
}) => RustLib.instance.api.crateApiInitCore(
  dbDir: dbDir,
  defaultInboxName: defaultInboxName,
);

Future<String> getSyncServerUrl() =>
    RustLib.instance.api.crateApiGetSyncServerUrl();

Future<void> setSyncServerUrl({required String serverUrl}) =>
    RustLib.instance.api.crateApiSetSyncServerUrl(serverUrl: serverUrl);

Future<AccountSessionStateDto> getAccountSessionState() =>
    RustLib.instance.api.crateApiGetAccountSessionState();

Future<AccountAuthResultDto> accountRegister({
  required String email,
  required String password,
  String? serverUrl,
  String? deviceName,
}) => RustLib.instance.api.crateApiAccountRegister(
  email: email,
  password: password,
  serverUrl: serverUrl,
  deviceName: deviceName,
);

Future<AccountAuthResultDto> accountLogin({
  required String email,
  required String password,
  String? serverUrl,
  String? deviceName,
}) => RustLib.instance.api.crateApiAccountLogin(
  email: email,
  password: password,
  serverUrl: serverUrl,
  deviceName: deviceName,
);

Future<void> accountLogout() => RustLib.instance.api.crateApiAccountLogout();

Future<SyncStatusDto> getSyncStatus() =>
    RustLib.instance.api.crateApiGetSyncStatus();

Future<SyncStatusDto> syncNow() => RustLib.instance.api.crateApiSyncNow();

/// Creates a list using the caller-provided fractional `sort_order`.
///
/// Automatic fractional index generation is a later M3 concern and is not done
/// in this bridge layer.
Future<ListDto> createList({required String name, required String sortOrder}) =>
    RustLib.instance.api.crateApiCreateList(name: name, sortOrder: sortOrder);

Future<List<ListDto>> getLists() => RustLib.instance.api.crateApiGetLists();

Future<List<ListDto>> getArchivedLists() =>
    RustLib.instance.api.crateApiGetArchivedLists();

Future<ListDto> renameList({required String listId, required String name}) =>
    RustLib.instance.api.crateApiRenameList(listId: listId, name: name);

Future<ListDto> archiveList({required String listId}) =>
    RustLib.instance.api.crateApiArchiveList(listId: listId);

Future<ListDto> unarchiveList({required String listId}) =>
    RustLib.instance.api.crateApiUnarchiveList(listId: listId);

/// Creates a task at the end of its sibling group using a domain-generated
/// fractional `sort_order`.
Future<TaskDto> createTask({
  required String listId,
  required String title,
  String? parentTaskId,
  PlatformInt64? dueAt,
  String? note,
}) => RustLib.instance.api.crateApiCreateTask(
  listId: listId,
  title: title,
  parentTaskId: parentTaskId,
  dueAt: dueAt,
  note: note,
);

Future<TaskDto> reorderTask({
  required String taskId,
  String? previousTaskId,
  String? nextTaskId,
}) => RustLib.instance.api.crateApiReorderTask(
  taskId: taskId,
  previousTaskId: previousTaskId,
  nextTaskId: nextTaskId,
);

Future<List<TaskDto>> getTasks({required String listId}) =>
    RustLib.instance.api.crateApiGetTasks(listId: listId);

Future<List<TaskDto>> searchTasks({required String query}) =>
    RustLib.instance.api.crateApiSearchTasks(query: query);

Future<List<HomeTaskDto>> getHomeTasks({
  required PlatformInt64 todayStartMs,
  required PlatformInt64 tomorrowStartMs,
}) => RustLib.instance.api.crateApiGetHomeTasks(
  todayStartMs: todayStartMs,
  tomorrowStartMs: tomorrowStartMs,
);

Future<int> countTaskDescendants({required String taskId}) =>
    RustLib.instance.api.crateApiCountTaskDescendants(taskId: taskId);

Future<int> countTasksInList({required String listId}) =>
    RustLib.instance.api.crateApiCountTasksInList(listId: listId);

Future<TaskDto> updateTask({
  required String taskId,
  required String title,
  required String note,
  required int priority,
  PlatformInt64? dueAt,
}) => RustLib.instance.api.crateApiUpdateTask(
  taskId: taskId,
  title: title,
  note: note,
  priority: priority,
  dueAt: dueAt,
);

Future<TaskDto> setTaskStatus({
  required String taskId,
  required String status,
  String? closedReason,
}) => RustLib.instance.api.crateApiSetTaskStatus(
  taskId: taskId,
  status: status,
  closedReason: closedReason,
);

Future<void> deleteTask({required String taskId}) =>
    RustLib.instance.api.crateApiDeleteTask(taskId: taskId);

Future<void> deleteList({required String listId}) =>
    RustLib.instance.api.crateApiDeleteList(listId: listId);

Future<TaskUndoDto?> getLatestTaskUndo() =>
    RustLib.instance.api.crateApiGetLatestTaskUndo();

Future<TaskDto> undoTaskOperation({required String undoId}) =>
    RustLib.instance.api.crateApiUndoTaskOperation(undoId: undoId);

Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiGetSetting(key: key);

Future<void> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiSetSetting(key: key, value: value);

Future<ReminderDto> setTaskReminder({
  required String taskId,
  required PlatformInt64 remindAt,
}) => RustLib.instance.api.crateApiSetTaskReminder(
  taskId: taskId,
  remindAt: remindAt,
);

Future<List<ReminderDto>> clearTaskReminders({required String taskId}) =>
    RustLib.instance.api.crateApiClearTaskReminders(taskId: taskId);

Future<List<ReminderDto>> getTaskReminders({required String taskId}) =>
    RustLib.instance.api.crateApiGetTaskReminders(taskId: taskId);

Future<List<ReminderDto>> getTaskSubtreeReminders({required String taskId}) =>
    RustLib.instance.api.crateApiGetTaskSubtreeReminders(taskId: taskId);

Future<List<ReminderDto>> getListReminders({required String listId}) =>
    RustLib.instance.api.crateApiGetListReminders(listId: listId);

Future<List<ReminderDto>> listPendingReminders({
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiListPendingReminders(nowMs: nowMs);

Future<ReminderDto> snoozeReminder({
  required String reminderId,
  required PlatformInt64 snoozedUntil,
}) => RustLib.instance.api.crateApiSnoozeReminder(
  reminderId: reminderId,
  snoozedUntil: snoozedUntil,
);

class AccountAuthResultDto {
  final AccountSessionStateDto session;
  final String? recoveryKey;

  const AccountAuthResultDto({required this.session, this.recoveryKey});

  @override
  int get hashCode => session.hashCode ^ recoveryKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountAuthResultDto &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          recoveryKey == other.recoveryKey;
}

class AccountSessionStateDto {
  final bool loggedIn;
  final String? email;
  final String? userId;
  final String? tenantId;
  final String? deviceId;

  const AccountSessionStateDto({
    required this.loggedIn,
    this.email,
    this.userId,
    this.tenantId,
    this.deviceId,
  });

  @override
  int get hashCode =>
      loggedIn.hashCode ^
      email.hashCode ^
      userId.hashCode ^
      tenantId.hashCode ^
      deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountSessionStateDto &&
          runtimeType == other.runtimeType &&
          loggedIn == other.loggedIn &&
          email == other.email &&
          userId == other.userId &&
          tenantId == other.tenantId &&
          deviceId == other.deviceId;
}

class HomeTaskDto {
  final TaskDto task;
  final String listName;
  final bool isHomeTarget;

  const HomeTaskDto({
    required this.task,
    required this.listName,
    required this.isHomeTarget,
  });

  @override
  int get hashCode => task.hashCode ^ listName.hashCode ^ isHomeTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeTaskDto &&
          runtimeType == other.runtimeType &&
          task == other.task &&
          listName == other.listName &&
          isHomeTarget == other.isHomeTarget;
}

class ListDto {
  final String id;
  final String name;
  final String color;
  final String icon;
  final String? orgId;
  final String sortOrder;
  final bool isDefault;
  final PlatformInt64? archivedAt;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const ListDto({
    required this.id,
    required this.name,
    required this.color,
    required this.icon,
    this.orgId,
    required this.sortOrder,
    required this.isDefault,
    this.archivedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      color.hashCode ^
      icon.hashCode ^
      orgId.hashCode ^
      sortOrder.hashCode ^
      isDefault.hashCode ^
      archivedAt.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          color == other.color &&
          icon == other.icon &&
          orgId == other.orgId &&
          sortOrder == other.sortOrder &&
          isDefault == other.isDefault &&
          archivedAt == other.archivedAt &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class ReminderDto {
  final String id;
  final String taskId;
  final PlatformInt64 remindAt;
  final PlatformInt64? snoozedUntil;
  final PlatformInt64 createdAt;

  const ReminderDto({
    required this.id,
    required this.taskId,
    required this.remindAt,
    this.snoozedUntil,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      taskId.hashCode ^
      remindAt.hashCode ^
      snoozedUntil.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReminderDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          taskId == other.taskId &&
          remindAt == other.remindAt &&
          snoozedUntil == other.snoozedUntil &&
          createdAt == other.createdAt;
}

class SyncStatusDto {
  final bool loggedIn;
  final bool running;
  final PlatformInt64? lastSuccessAt;
  final PlatformInt64? lastFailureAt;
  final String? lastError;
  final int pushedCount;
  final int pushAckedCount;
  final int pushSupersededCount;
  final int pulledCount;
  final int appliedCount;
  final int deletedCount;
  final int decryptFailedCount;
  final int repushCount;

  const SyncStatusDto({
    required this.loggedIn,
    required this.running,
    this.lastSuccessAt,
    this.lastFailureAt,
    this.lastError,
    required this.pushedCount,
    required this.pushAckedCount,
    required this.pushSupersededCount,
    required this.pulledCount,
    required this.appliedCount,
    required this.deletedCount,
    required this.decryptFailedCount,
    required this.repushCount,
  });

  @override
  int get hashCode =>
      loggedIn.hashCode ^
      running.hashCode ^
      lastSuccessAt.hashCode ^
      lastFailureAt.hashCode ^
      lastError.hashCode ^
      pushedCount.hashCode ^
      pushAckedCount.hashCode ^
      pushSupersededCount.hashCode ^
      pulledCount.hashCode ^
      appliedCount.hashCode ^
      deletedCount.hashCode ^
      decryptFailedCount.hashCode ^
      repushCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusDto &&
          runtimeType == other.runtimeType &&
          loggedIn == other.loggedIn &&
          running == other.running &&
          lastSuccessAt == other.lastSuccessAt &&
          lastFailureAt == other.lastFailureAt &&
          lastError == other.lastError &&
          pushedCount == other.pushedCount &&
          pushAckedCount == other.pushAckedCount &&
          pushSupersededCount == other.pushSupersededCount &&
          pulledCount == other.pulledCount &&
          appliedCount == other.appliedCount &&
          deletedCount == other.deletedCount &&
          decryptFailedCount == other.decryptFailedCount &&
          repushCount == other.repushCount;
}

class TaskDto {
  final String id;
  final String listId;
  final String? parentTaskId;
  final String title;
  final String note;
  final String status;
  final int priority;
  final PlatformInt64? dueAt;
  final PlatformInt64? scheduledAt;
  final int? estimatedMinutes;
  final String sortOrder;
  final PlatformInt64? completedAt;
  final String? closedReason;
  final PlatformInt64? deletedAt;
  final String? assignee;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const TaskDto({
    required this.id,
    required this.listId,
    this.parentTaskId,
    required this.title,
    required this.note,
    required this.status,
    required this.priority,
    this.dueAt,
    this.scheduledAt,
    this.estimatedMinutes,
    required this.sortOrder,
    this.completedAt,
    this.closedReason,
    this.deletedAt,
    this.assignee,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      listId.hashCode ^
      parentTaskId.hashCode ^
      title.hashCode ^
      note.hashCode ^
      status.hashCode ^
      priority.hashCode ^
      dueAt.hashCode ^
      scheduledAt.hashCode ^
      estimatedMinutes.hashCode ^
      sortOrder.hashCode ^
      completedAt.hashCode ^
      closedReason.hashCode ^
      deletedAt.hashCode ^
      assignee.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          listId == other.listId &&
          parentTaskId == other.parentTaskId &&
          title == other.title &&
          note == other.note &&
          status == other.status &&
          priority == other.priority &&
          dueAt == other.dueAt &&
          scheduledAt == other.scheduledAt &&
          estimatedMinutes == other.estimatedMinutes &&
          sortOrder == other.sortOrder &&
          completedAt == other.completedAt &&
          closedReason == other.closedReason &&
          deletedAt == other.deletedAt &&
          assignee == other.assignee &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class TaskUndoDto {
  final String id;
  final String operationType;
  final String taskId;
  final String listId;
  final String taskTitle;
  final PlatformInt64 createdAt;

  const TaskUndoDto({
    required this.id,
    required this.operationType,
    required this.taskId,
    required this.listId,
    required this.taskTitle,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      operationType.hashCode ^
      taskId.hashCode ^
      listId.hashCode ^
      taskTitle.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskUndoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          operationType == other.operationType &&
          taskId == other.taskId &&
          listId == other.listId &&
          taskTitle == other.taskTitle &&
          createdAt == other.createdAt;
}
