// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core_state`, `count_to_i32`, `home_task_to_dto`, `list_to_dto`, `load_reorder_boundary`, `now_ms`, `parse_status`, `parse_uuid`, `status_to_string`, `task_to_dto`, `task_undo_operation_to_string`, `task_undo_to_dto`, `with_list_repository`, `with_task_repository`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CoreState`

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiGreet(name: name);

Future<String> createDraftTask({required String title}) =>
    RustLib.instance.api.crateApiCreateDraftTask(title: title);

/// Initializes Todori core for the process using `db_dir`.
///
/// This creates or loads a development plaintext `device.key`, derives the
/// SQLCipher key, initializes `<db_dir>/todori.db`, and stores only the DB path
/// plus derived key in process-global state. Reinitializing with the same DB
/// path succeeds idempotently; reinitializing with a different DB path returns
/// an error because `OnceLock` cannot safely swap process-global state.
Future<void> initCore({
  required String dbDir,
  required String defaultInboxName,
}) => RustLib.instance.api.crateApiInitCore(
  dbDir: dbDir,
  defaultInboxName: defaultInboxName,
);

/// Creates a list using the caller-provided fractional `sort_order`.
///
/// Automatic fractional index generation is a later M3 concern and is not done
/// in this bridge layer.
Future<ListDto> createList({required String name, required String sortOrder}) =>
    RustLib.instance.api.crateApiCreateList(name: name, sortOrder: sortOrder);

Future<List<ListDto>> getLists() => RustLib.instance.api.crateApiGetLists();

Future<List<ListDto>> getArchivedLists() =>
    RustLib.instance.api.crateApiGetArchivedLists();

Future<ListDto> renameList({required String listId, required String name}) =>
    RustLib.instance.api.crateApiRenameList(listId: listId, name: name);

Future<ListDto> archiveList({required String listId}) =>
    RustLib.instance.api.crateApiArchiveList(listId: listId);

Future<ListDto> unarchiveList({required String listId}) =>
    RustLib.instance.api.crateApiUnarchiveList(listId: listId);

/// Creates a task at the end of its sibling group using a domain-generated
/// fractional `sort_order`.
Future<TaskDto> createTask({
  required String listId,
  required String title,
  String? parentTaskId,
  PlatformInt64? dueAt,
  String? note,
}) => RustLib.instance.api.crateApiCreateTask(
  listId: listId,
  title: title,
  parentTaskId: parentTaskId,
  dueAt: dueAt,
  note: note,
);

Future<TaskDto> reorderTask({
  required String taskId,
  String? previousTaskId,
  String? nextTaskId,
}) => RustLib.instance.api.crateApiReorderTask(
  taskId: taskId,
  previousTaskId: previousTaskId,
  nextTaskId: nextTaskId,
);

Future<List<TaskDto>> getTasks({required String listId}) =>
    RustLib.instance.api.crateApiGetTasks(listId: listId);

Future<List<HomeTaskDto>> getHomeTasks({
  required PlatformInt64 todayStartMs,
  required PlatformInt64 tomorrowStartMs,
}) => RustLib.instance.api.crateApiGetHomeTasks(
  todayStartMs: todayStartMs,
  tomorrowStartMs: tomorrowStartMs,
);

Future<int> countTaskDescendants({required String taskId}) =>
    RustLib.instance.api.crateApiCountTaskDescendants(taskId: taskId);

Future<int> countTasksInList({required String listId}) =>
    RustLib.instance.api.crateApiCountTasksInList(listId: listId);

Future<TaskDto> updateTask({
  required String taskId,
  required String title,
  required String note,
  required int priority,
  PlatformInt64? dueAt,
}) => RustLib.instance.api.crateApiUpdateTask(
  taskId: taskId,
  title: title,
  note: note,
  priority: priority,
  dueAt: dueAt,
);

Future<TaskDto> setTaskStatus({
  required String taskId,
  required String status,
  String? closedReason,
}) => RustLib.instance.api.crateApiSetTaskStatus(
  taskId: taskId,
  status: status,
  closedReason: closedReason,
);

Future<void> deleteTask({required String taskId}) =>
    RustLib.instance.api.crateApiDeleteTask(taskId: taskId);

Future<void> deleteList({required String listId}) =>
    RustLib.instance.api.crateApiDeleteList(listId: listId);

Future<TaskUndoDto?> getLatestTaskUndo() =>
    RustLib.instance.api.crateApiGetLatestTaskUndo();

Future<TaskDto> undoTaskOperation({required String undoId}) =>
    RustLib.instance.api.crateApiUndoTaskOperation(undoId: undoId);

class HomeTaskDto {
  final TaskDto task;
  final String listName;
  final bool isHomeTarget;

  const HomeTaskDto({
    required this.task,
    required this.listName,
    required this.isHomeTarget,
  });

  @override
  int get hashCode => task.hashCode ^ listName.hashCode ^ isHomeTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HomeTaskDto &&
          runtimeType == other.runtimeType &&
          task == other.task &&
          listName == other.listName &&
          isHomeTarget == other.isHomeTarget;
}

class ListDto {
  final String id;
  final String name;
  final String color;
  final String icon;
  final String? orgId;
  final String sortOrder;
  final bool isDefault;
  final PlatformInt64? archivedAt;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const ListDto({
    required this.id,
    required this.name,
    required this.color,
    required this.icon,
    this.orgId,
    required this.sortOrder,
    required this.isDefault,
    this.archivedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      color.hashCode ^
      icon.hashCode ^
      orgId.hashCode ^
      sortOrder.hashCode ^
      isDefault.hashCode ^
      archivedAt.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          color == other.color &&
          icon == other.icon &&
          orgId == other.orgId &&
          sortOrder == other.sortOrder &&
          isDefault == other.isDefault &&
          archivedAt == other.archivedAt &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class TaskDto {
  final String id;
  final String listId;
  final String? parentTaskId;
  final String title;
  final String note;
  final String status;
  final int priority;
  final PlatformInt64? dueAt;
  final PlatformInt64? scheduledAt;
  final int? estimatedMinutes;
  final String sortOrder;
  final PlatformInt64? completedAt;
  final String? closedReason;
  final PlatformInt64? deletedAt;
  final String? assignee;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const TaskDto({
    required this.id,
    required this.listId,
    this.parentTaskId,
    required this.title,
    required this.note,
    required this.status,
    required this.priority,
    this.dueAt,
    this.scheduledAt,
    this.estimatedMinutes,
    required this.sortOrder,
    this.completedAt,
    this.closedReason,
    this.deletedAt,
    this.assignee,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      listId.hashCode ^
      parentTaskId.hashCode ^
      title.hashCode ^
      note.hashCode ^
      status.hashCode ^
      priority.hashCode ^
      dueAt.hashCode ^
      scheduledAt.hashCode ^
      estimatedMinutes.hashCode ^
      sortOrder.hashCode ^
      completedAt.hashCode ^
      closedReason.hashCode ^
      deletedAt.hashCode ^
      assignee.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          listId == other.listId &&
          parentTaskId == other.parentTaskId &&
          title == other.title &&
          note == other.note &&
          status == other.status &&
          priority == other.priority &&
          dueAt == other.dueAt &&
          scheduledAt == other.scheduledAt &&
          estimatedMinutes == other.estimatedMinutes &&
          sortOrder == other.sortOrder &&
          completedAt == other.completedAt &&
          closedReason == other.closedReason &&
          deletedAt == other.deletedAt &&
          assignee == other.assignee &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class TaskUndoDto {
  final String id;
  final String operationType;
  final String taskId;
  final String listId;
  final String taskTitle;
  final PlatformInt64 createdAt;

  const TaskUndoDto({
    required this.id,
    required this.operationType,
    required this.taskId,
    required this.listId,
    required this.taskTitle,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      operationType.hashCode ^
      taskId.hashCode ^
      listId.hashCode ^
      taskTitle.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskUndoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          operationType == other.operationType &&
          taskId == other.taskId &&
          listId == other.listId &&
          taskTitle == other.taskTitle &&
          createdAt == other.createdAt;
}
