// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1100881644;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'todori_app_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiCreateDraftTask({required String title});

  Future<ListDto> crateApiCreateList({
    required String name,
    required String sortOrder,
  });

  Future<TaskDto> crateApiCreateTask({
    required String listId,
    required String title,
    String? parentTaskId,
  });

  Future<TaskUndoDto?> crateApiGetLatestTaskUndo();

  Future<List<ListDto>> crateApiGetLists();

  Future<List<TaskDto>> crateApiGetTasks({required String listId});

  Future<List<TaskDto>> crateApiGetTrashedTasks();

  Future<String> crateApiGreet({required String name});

  Future<void> crateApiInitCore({required String dbDir});

  Future<TaskDto> crateApiReorderTask({
    required String taskId,
    String? previousTaskId,
    String? nextTaskId,
  });

  Future<TaskDto> crateApiRestoreTask({required String taskId});

  Future<TaskDto> crateApiSetTaskStatus({
    required String taskId,
    required String status,
    String? closedReason,
  });

  Future<TaskDto> crateApiTrashTask({required String taskId});

  Future<TaskDto> crateApiUndoTaskOperation({required String undoId});

  Future<TaskDto> crateApiUpdateTask({
    required String taskId,
    required String title,
    required String note,
    required int priority,
    PlatformInt64? dueAt,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiCreateDraftTask({required String title}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCreateDraftTaskConstMeta,
        argValues: [title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateDraftTaskConstMeta =>
      const TaskConstMeta(debugName: "create_draft_task", argNames: ["title"]);

  @override
  Future<ListDto> crateApiCreateList({
    required String name,
    required String sortOrder,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(sortOrder, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateListConstMeta,
        argValues: [name, sortOrder],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateListConstMeta => const TaskConstMeta(
    debugName: "create_list",
    argNames: ["name", "sortOrder"],
  );

  @override
  Future<TaskDto> crateApiCreateTask({
    required String listId,
    required String title,
    String? parentTaskId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(listId, serializer);
          sse_encode_String(title, serializer);
          sse_encode_opt_String(parentTaskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateTaskConstMeta,
        argValues: [listId, title, parentTaskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateTaskConstMeta => const TaskConstMeta(
    debugName: "create_task",
    argNames: ["listId", "title", "parentTaskId"],
  );

  @override
  Future<TaskUndoDto?> crateApiGetLatestTaskUndo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_task_undo_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetLatestTaskUndoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLatestTaskUndoConstMeta =>
      const TaskConstMeta(debugName: "get_latest_task_undo", argNames: []);

  @override
  Future<List<ListDto>> crateApiGetLists() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetListsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetListsConstMeta =>
      const TaskConstMeta(debugName: "get_lists", argNames: []);

  @override
  Future<List<TaskDto>> crateApiGetTasks({required String listId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(listId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_task_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetTasksConstMeta,
        argValues: [listId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetTasksConstMeta =>
      const TaskConstMeta(debugName: "get_tasks", argNames: ["listId"]);

  @override
  Future<List<TaskDto>> crateApiGetTrashedTasks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_task_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetTrashedTasksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetTrashedTasksConstMeta =>
      const TaskConstMeta(debugName: "get_trashed_tasks", argNames: []);

  @override
  Future<String> crateApiGreet({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiInitCore({required String dbDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInitCoreConstMeta,
        argValues: [dbDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitCoreConstMeta =>
      const TaskConstMeta(debugName: "init_core", argNames: ["dbDir"]);

  @override
  Future<TaskDto> crateApiReorderTask({
    required String taskId,
    String? previousTaskId,
    String? nextTaskId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          sse_encode_opt_String(previousTaskId, serializer);
          sse_encode_opt_String(nextTaskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReorderTaskConstMeta,
        argValues: [taskId, previousTaskId, nextTaskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReorderTaskConstMeta => const TaskConstMeta(
    debugName: "reorder_task",
    argNames: ["taskId", "previousTaskId", "nextTaskId"],
  );

  @override
  Future<TaskDto> crateApiRestoreTask({required String taskId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRestoreTaskConstMeta,
        argValues: [taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRestoreTaskConstMeta =>
      const TaskConstMeta(debugName: "restore_task", argNames: ["taskId"]);

  @override
  Future<TaskDto> crateApiSetTaskStatus({
    required String taskId,
    required String status,
    String? closedReason,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          sse_encode_String(status, serializer);
          sse_encode_opt_String(closedReason, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetTaskStatusConstMeta,
        argValues: [taskId, status, closedReason],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetTaskStatusConstMeta => const TaskConstMeta(
    debugName: "set_task_status",
    argNames: ["taskId", "status", "closedReason"],
  );

  @override
  Future<TaskDto> crateApiTrashTask({required String taskId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTrashTaskConstMeta,
        argValues: [taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTrashTaskConstMeta =>
      const TaskConstMeta(debugName: "trash_task", argNames: ["taskId"]);

  @override
  Future<TaskDto> crateApiUndoTaskOperation({required String undoId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(undoId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUndoTaskOperationConstMeta,
        argValues: [undoId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUndoTaskOperationConstMeta => const TaskConstMeta(
    debugName: "undo_task_operation",
    argNames: ["undoId"],
  );

  @override
  Future<TaskDto> crateApiUpdateTask({
    required String taskId,
    required String title,
    required String note,
    required int priority,
    PlatformInt64? dueAt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(note, serializer);
          sse_encode_i_32(priority, serializer);
          sse_encode_opt_box_autoadd_i_64(dueAt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUpdateTaskConstMeta,
        argValues: [taskId, title, note, priority, dueAt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateTaskConstMeta => const TaskConstMeta(
    debugName: "update_task",
    argNames: ["taskId", "title", "note", "priority", "dueAt"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  TaskUndoDto dco_decode_box_autoadd_task_undo_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_task_undo_dto(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ListDto dco_decode_list_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ListDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      color: dco_decode_String(arr[2]),
      icon: dco_decode_String(arr[3]),
      orgId: dco_decode_opt_String(arr[4]),
      sortOrder: dco_decode_String(arr[5]),
      createdAt: dco_decode_i_64(arr[6]),
      updatedAt: dco_decode_i_64(arr[7]),
    );
  }

  @protected
  List<ListDto> dco_decode_list_list_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TaskDto> dco_decode_list_task_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_task_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  TaskUndoDto? dco_decode_opt_box_autoadd_task_undo_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_task_undo_dto(raw);
  }

  @protected
  TaskDto dco_decode_task_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return TaskDto(
      id: dco_decode_String(arr[0]),
      listId: dco_decode_String(arr[1]),
      parentTaskId: dco_decode_opt_String(arr[2]),
      title: dco_decode_String(arr[3]),
      note: dco_decode_String(arr[4]),
      status: dco_decode_String(arr[5]),
      priority: dco_decode_i_32(arr[6]),
      dueAt: dco_decode_opt_box_autoadd_i_64(arr[7]),
      scheduledAt: dco_decode_opt_box_autoadd_i_64(arr[8]),
      estimatedMinutes: dco_decode_opt_box_autoadd_i_32(arr[9]),
      sortOrder: dco_decode_String(arr[10]),
      completedAt: dco_decode_opt_box_autoadd_i_64(arr[11]),
      closedReason: dco_decode_opt_String(arr[12]),
      deletedAt: dco_decode_opt_box_autoadd_i_64(arr[13]),
      assignee: dco_decode_opt_String(arr[14]),
      createdAt: dco_decode_i_64(arr[15]),
      updatedAt: dco_decode_i_64(arr[16]),
    );
  }

  @protected
  TaskUndoDto dco_decode_task_undo_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TaskUndoDto(
      id: dco_decode_String(arr[0]),
      operationType: dco_decode_String(arr[1]),
      taskId: dco_decode_String(arr[2]),
      listId: dco_decode_String(arr[3]),
      taskTitle: dco_decode_String(arr[4]),
      createdAt: dco_decode_i_64(arr[5]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  TaskUndoDto sse_decode_box_autoadd_task_undo_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_task_undo_dto(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ListDto sse_decode_list_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_color = sse_decode_String(deserializer);
    var var_icon = sse_decode_String(deserializer);
    var var_orgId = sse_decode_opt_String(deserializer);
    var var_sortOrder = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return ListDto(
      id: var_id,
      name: var_name,
      color: var_color,
      icon: var_icon,
      orgId: var_orgId,
      sortOrder: var_sortOrder,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  List<ListDto> sse_decode_list_list_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ListDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TaskDto> sse_decode_list_task_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TaskDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_task_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TaskUndoDto? sse_decode_opt_box_autoadd_task_undo_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_task_undo_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TaskDto sse_decode_task_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_listId = sse_decode_String(deserializer);
    var var_parentTaskId = sse_decode_opt_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_note = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_priority = sse_decode_i_32(deserializer);
    var var_dueAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_scheduledAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_estimatedMinutes = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_sortOrder = sse_decode_String(deserializer);
    var var_completedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_closedReason = sse_decode_opt_String(deserializer);
    var var_deletedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_assignee = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return TaskDto(
      id: var_id,
      listId: var_listId,
      parentTaskId: var_parentTaskId,
      title: var_title,
      note: var_note,
      status: var_status,
      priority: var_priority,
      dueAt: var_dueAt,
      scheduledAt: var_scheduledAt,
      estimatedMinutes: var_estimatedMinutes,
      sortOrder: var_sortOrder,
      completedAt: var_completedAt,
      closedReason: var_closedReason,
      deletedAt: var_deletedAt,
      assignee: var_assignee,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  TaskUndoDto sse_decode_task_undo_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_operationType = sse_decode_String(deserializer);
    var var_taskId = sse_decode_String(deserializer);
    var var_listId = sse_decode_String(deserializer);
    var var_taskTitle = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return TaskUndoDto(
      id: var_id,
      operationType: var_operationType,
      taskId: var_taskId,
      listId: var_listId,
      taskTitle: var_taskTitle,
      createdAt: var_createdAt,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_task_undo_dto(
    TaskUndoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_task_undo_dto(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_dto(ListDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.color, serializer);
    sse_encode_String(self.icon, serializer);
    sse_encode_opt_String(self.orgId, serializer);
    sse_encode_String(self.sortOrder, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_list_list_dto(List<ListDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_task_dto(List<TaskDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_task_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_task_undo_dto(
    TaskUndoDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_task_undo_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_task_dto(TaskDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.listId, serializer);
    sse_encode_opt_String(self.parentTaskId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.note, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_i_32(self.priority, serializer);
    sse_encode_opt_box_autoadd_i_64(self.dueAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.scheduledAt, serializer);
    sse_encode_opt_box_autoadd_i_32(self.estimatedMinutes, serializer);
    sse_encode_String(self.sortOrder, serializer);
    sse_encode_opt_box_autoadd_i_64(self.completedAt, serializer);
    sse_encode_opt_String(self.closedReason, serializer);
    sse_encode_opt_box_autoadd_i_64(self.deletedAt, serializer);
    sse_encode_opt_String(self.assignee, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_task_undo_dto(TaskUndoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.operationType, serializer);
    sse_encode_String(self.taskId, serializer);
    sse_encode_String(self.listId, serializer);
    sse_encode_String(self.taskTitle, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
