// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountAuthResultDto dco_decode_account_auth_result_dto(dynamic raw);

  @protected
  AccountSessionStateDto dco_decode_account_session_state_dto(dynamic raw);

  @protected
  ActiveTimerSessionDto dco_decode_active_timer_session_dto(dynamic raw);

  @protected
  ActiveTimerStartOutcomeDto dco_decode_active_timer_start_outcome_dto(
    dynamic raw,
  );

  @protected
  BillingStateDto dco_decode_billing_state_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  ActiveTimerSessionDto dco_decode_box_autoadd_active_timer_session_dto(
    dynamic raw,
  );

  @protected
  BillingStateDto dco_decode_box_autoadd_billing_state_dto(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CalendarRangeInput dco_decode_box_autoadd_calendar_range_input(dynamic raw);

  @protected
  CompletedTimerSessionDto dco_decode_box_autoadd_completed_timer_session_dto(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  SyncStatusDto dco_decode_box_autoadd_sync_status_dto(dynamic raw);

  @protected
  TaskDueDto dco_decode_box_autoadd_task_due_dto(dynamic raw);

  @protected
  TaskDueInput dco_decode_box_autoadd_task_due_input(dynamic raw);

  @protected
  TaskUndoDto dco_decode_box_autoadd_task_undo_dto(dynamic raw);

  @protected
  CalendarOccurrenceDto dco_decode_calendar_occurrence_dto(dynamic raw);

  @protected
  CalendarOccurrenceKindDto dco_decode_calendar_occurrence_kind_dto(
    dynamic raw,
  );

  @protected
  CalendarRangeInput dco_decode_calendar_range_input(dynamic raw);

  @protected
  CompletedTimerSessionDto dco_decode_completed_timer_session_dto(dynamic raw);

  @protected
  HomeTaskDto dco_decode_home_task_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<CalendarOccurrenceDto> dco_decode_list_calendar_occurrence_dto(
    dynamic raw,
  );

  @protected
  List<CompletedTimerSessionDto> dco_decode_list_completed_timer_session_dto(
    dynamic raw,
  );

  @protected
  ListDto dco_decode_list_dto(dynamic raw);

  @protected
  List<HomeTaskDto> dco_decode_list_home_task_dto(dynamic raw);

  @protected
  List<ListDto> dco_decode_list_list_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReminderDto> dco_decode_list_reminder_dto(dynamic raw);

  @protected
  List<ScheduleDto> dco_decode_list_schedule_dto(dynamic raw);

  @protected
  List<TaskDto> dco_decode_list_task_dto(dynamic raw);

  @protected
  List<TemplateDto> dco_decode_list_template_dto(dynamic raw);

  @protected
  List<TemplateNodeDto> dco_decode_list_template_node_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  ActiveTimerSessionDto? dco_decode_opt_box_autoadd_active_timer_session_dto(
    dynamic raw,
  );

  @protected
  BillingStateDto? dco_decode_opt_box_autoadd_billing_state_dto(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  TaskDueDto? dco_decode_opt_box_autoadd_task_due_dto(dynamic raw);

  @protected
  TaskDueInput? dco_decode_opt_box_autoadd_task_due_input(dynamic raw);

  @protected
  TaskUndoDto? dco_decode_opt_box_autoadd_task_undo_dto(dynamic raw);

  @protected
  OrganizationSafetyStateDto dco_decode_organization_safety_state_dto(
    dynamic raw,
  );

  @protected
  RealtimeTicketDto dco_decode_realtime_ticket_dto(dynamic raw);

  @protected
  ReminderDto dco_decode_reminder_dto(dynamic raw);

  @protected
  ScheduleDto dco_decode_schedule_dto(dynamic raw);

  @protected
  SettlementSummaryDto dco_decode_settlement_summary_dto(dynamic raw);

  @protected
  StreakDto dco_decode_streak_dto(dynamic raw);

  @protected
  SyncNowOutcomeDto dco_decode_sync_now_outcome_dto(dynamic raw);

  @protected
  SyncStatusDto dco_decode_sync_status_dto(dynamic raw);

  @protected
  TaskDto dco_decode_task_dto(dynamic raw);

  @protected
  TaskDueDto dco_decode_task_due_dto(dynamic raw);

  @protected
  TaskDueInput dco_decode_task_due_input(dynamic raw);

  @protected
  TaskUndoDto dco_decode_task_undo_dto(dynamic raw);

  @protected
  TemplateDto dco_decode_template_dto(dynamic raw);

  @protected
  TemplateNodeDto dco_decode_template_node_dto(dynamic raw);

  @protected
  TimerFinishKindDto dco_decode_timer_finish_kind_dto(dynamic raw);

  @protected
  TimerModeDto dco_decode_timer_mode_dto(dynamic raw);

  @protected
  TimerPhaseDto dco_decode_timer_phase_dto(dynamic raw);

  @protected
  TimerRunStateDto dco_decode_timer_run_state_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountAuthResultDto sse_decode_account_auth_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  AccountSessionStateDto sse_decode_account_session_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  ActiveTimerSessionDto sse_decode_active_timer_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  ActiveTimerStartOutcomeDto sse_decode_active_timer_start_outcome_dto(
    SseDeserializer deserializer,
  );

  @protected
  BillingStateDto sse_decode_billing_state_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  ActiveTimerSessionDto sse_decode_box_autoadd_active_timer_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  BillingStateDto sse_decode_box_autoadd_billing_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CalendarRangeInput sse_decode_box_autoadd_calendar_range_input(
    SseDeserializer deserializer,
  );

  @protected
  CompletedTimerSessionDto sse_decode_box_autoadd_completed_timer_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SyncStatusDto sse_decode_box_autoadd_sync_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  TaskDueDto sse_decode_box_autoadd_task_due_dto(SseDeserializer deserializer);

  @protected
  TaskDueInput sse_decode_box_autoadd_task_due_input(
    SseDeserializer deserializer,
  );

  @protected
  TaskUndoDto sse_decode_box_autoadd_task_undo_dto(
    SseDeserializer deserializer,
  );

  @protected
  CalendarOccurrenceDto sse_decode_calendar_occurrence_dto(
    SseDeserializer deserializer,
  );

  @protected
  CalendarOccurrenceKindDto sse_decode_calendar_occurrence_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  CalendarRangeInput sse_decode_calendar_range_input(
    SseDeserializer deserializer,
  );

  @protected
  CompletedTimerSessionDto sse_decode_completed_timer_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  HomeTaskDto sse_decode_home_task_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<CalendarOccurrenceDto> sse_decode_list_calendar_occurrence_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<CompletedTimerSessionDto> sse_decode_list_completed_timer_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  ListDto sse_decode_list_dto(SseDeserializer deserializer);

  @protected
  List<HomeTaskDto> sse_decode_list_home_task_dto(SseDeserializer deserializer);

  @protected
  List<ListDto> sse_decode_list_list_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReminderDto> sse_decode_list_reminder_dto(SseDeserializer deserializer);

  @protected
  List<ScheduleDto> sse_decode_list_schedule_dto(SseDeserializer deserializer);

  @protected
  List<TaskDto> sse_decode_list_task_dto(SseDeserializer deserializer);

  @protected
  List<TemplateDto> sse_decode_list_template_dto(SseDeserializer deserializer);

  @protected
  List<TemplateNodeDto> sse_decode_list_template_node_dto(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  ActiveTimerSessionDto? sse_decode_opt_box_autoadd_active_timer_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  BillingStateDto? sse_decode_opt_box_autoadd_billing_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  TaskDueDto? sse_decode_opt_box_autoadd_task_due_dto(
    SseDeserializer deserializer,
  );

  @protected
  TaskDueInput? sse_decode_opt_box_autoadd_task_due_input(
    SseDeserializer deserializer,
  );

  @protected
  TaskUndoDto? sse_decode_opt_box_autoadd_task_undo_dto(
    SseDeserializer deserializer,
  );

  @protected
  OrganizationSafetyStateDto sse_decode_organization_safety_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  RealtimeTicketDto sse_decode_realtime_ticket_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReminderDto sse_decode_reminder_dto(SseDeserializer deserializer);

  @protected
  ScheduleDto sse_decode_schedule_dto(SseDeserializer deserializer);

  @protected
  SettlementSummaryDto sse_decode_settlement_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  StreakDto sse_decode_streak_dto(SseDeserializer deserializer);

  @protected
  SyncNowOutcomeDto sse_decode_sync_now_outcome_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncStatusDto sse_decode_sync_status_dto(SseDeserializer deserializer);

  @protected
  TaskDto sse_decode_task_dto(SseDeserializer deserializer);

  @protected
  TaskDueDto sse_decode_task_due_dto(SseDeserializer deserializer);

  @protected
  TaskDueInput sse_decode_task_due_input(SseDeserializer deserializer);

  @protected
  TaskUndoDto sse_decode_task_undo_dto(SseDeserializer deserializer);

  @protected
  TemplateDto sse_decode_template_dto(SseDeserializer deserializer);

  @protected
  TemplateNodeDto sse_decode_template_node_dto(SseDeserializer deserializer);

  @protected
  TimerFinishKindDto sse_decode_timer_finish_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  TimerModeDto sse_decode_timer_mode_dto(SseDeserializer deserializer);

  @protected
  TimerPhaseDto sse_decode_timer_phase_dto(SseDeserializer deserializer);

  @protected
  TimerRunStateDto sse_decode_timer_run_state_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_auth_result_dto(
    AccountAuthResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_account_session_state_dto(
    AccountSessionStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_active_timer_session_dto(
    ActiveTimerSessionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_active_timer_start_outcome_dto(
    ActiveTimerStartOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_billing_state_dto(
    BillingStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_active_timer_session_dto(
    ActiveTimerSessionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_billing_state_dto(
    BillingStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_calendar_range_input(
    CalendarRangeInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_completed_timer_session_dto(
    CompletedTimerSessionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_status_dto(
    SyncStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_task_due_dto(
    TaskDueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_task_due_input(
    TaskDueInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_task_undo_dto(
    TaskUndoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_calendar_occurrence_dto(
    CalendarOccurrenceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_calendar_occurrence_kind_dto(
    CalendarOccurrenceKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_calendar_range_input(
    CalendarRangeInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_completed_timer_session_dto(
    CompletedTimerSessionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_home_task_dto(HomeTaskDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_calendar_occurrence_dto(
    List<CalendarOccurrenceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_completed_timer_session_dto(
    List<CompletedTimerSessionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dto(ListDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_home_task_dto(
    List<HomeTaskDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_dto(List<ListDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reminder_dto(
    List<ReminderDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_schedule_dto(
    List<ScheduleDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_task_dto(List<TaskDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_template_dto(
    List<TemplateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_template_node_dto(
    List<TemplateNodeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_active_timer_session_dto(
    ActiveTimerSessionDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_billing_state_dto(
    BillingStateDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_task_due_dto(
    TaskDueDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_task_due_input(
    TaskDueInput? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_task_undo_dto(
    TaskUndoDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_organization_safety_state_dto(
    OrganizationSafetyStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_realtime_ticket_dto(
    RealtimeTicketDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reminder_dto(ReminderDto self, SseSerializer serializer);

  @protected
  void sse_encode_schedule_dto(ScheduleDto self, SseSerializer serializer);

  @protected
  void sse_encode_settlement_summary_dto(
    SettlementSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_streak_dto(StreakDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_now_outcome_dto(
    SyncNowOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_status_dto(SyncStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_task_dto(TaskDto self, SseSerializer serializer);

  @protected
  void sse_encode_task_due_dto(TaskDueDto self, SseSerializer serializer);

  @protected
  void sse_encode_task_due_input(TaskDueInput self, SseSerializer serializer);

  @protected
  void sse_encode_task_undo_dto(TaskUndoDto self, SseSerializer serializer);

  @protected
  void sse_encode_template_dto(TemplateDto self, SseSerializer serializer);

  @protected
  void sse_encode_template_node_dto(
    TemplateNodeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timer_finish_kind_dto(
    TimerFinishKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timer_mode_dto(TimerModeDto self, SseSerializer serializer);

  @protected
  void sse_encode_timer_phase_dto(TimerPhaseDto self, SseSerializer serializer);

  @protected
  void sse_encode_timer_run_state_dto(
    TimerRunStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
