import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:todori/src/core/bridge_service.dart';
import 'package:todori/src/core/task_tree.dart';
import 'package:todori/src/rust/api.dart' show ListDto, TaskDto, TaskUndoDto;

/// The [BridgeService] used by the app.
///
/// Defaults to [FrbBridgeService] (the real native bridge). Widget tests
/// override this with an in-memory fake via
/// `ProviderScope(overrides: [bridgeServiceProvider.overrideWithValue(fake)])`
/// so no test depends on the native Rust library or `initCore`.
final bridgeServiceProvider = Provider<BridgeService>(
  (ref) => const FrbBridgeService(),
);

/// Generates a placeholder, monotonically-appending sort order string (e.g.
/// `a0`, `a1`, `a2`, ...) for newly created lists in this UI skeleton.
///
/// This is intentionally NOT a real fractional-index implementation: it
/// cannot express "insert between two existing items" or rebalance existing
/// values. Task sort orders are generated by the Rust/domain layer.
String nextSortOrder(int existingItemCount) => 'a$existingItemCount';

/// Manages the list of [ListDto]s shown on the lists screen.
///
/// Invalidate strategy: [createList] performs the bridge call first, then
/// calls `ref.invalidateSelf()`, which re-runs [build] and re-fetches
/// `getLists()`. Any widget that does `ref.watch(listsProvider)` is rebuilt
/// automatically with the refreshed `AsyncValue`.
class ListsNotifier extends AsyncNotifier<List<ListDto>> {
  @override
  FutureOr<List<ListDto>> build() {
    return ref.watch(bridgeServiceProvider).getLists();
  }

  /// Creates a new list named `name` and refreshes [listsProvider].
  Future<void> createList(String name) async {
    final bridge = ref.read(bridgeServiceProvider);
    final sortOrder = nextSortOrder(state.value?.length ?? 0);
    await bridge.createList(name: name, sortOrder: sortOrder);
    ref.invalidateSelf();
  }

  /// Renames `listId` and refreshes [listsProvider].
  Future<void> renameList(String listId, String name) async {
    final bridge = ref.read(bridgeServiceProvider);
    await bridge.renameList(listId: listId, name: name);
    ref.invalidateSelf();
  }

  /// Archives `listId` and refreshes active and archived list collections.
  Future<void> archiveList(String listId) async {
    final bridge = ref.read(bridgeServiceProvider);
    await bridge.archiveList(listId: listId);
    ref.invalidateSelf();
    ref.invalidate(archivedListsProvider);
  }

  Future<int> countTasks(String listId) {
    return ref.read(bridgeServiceProvider).countTasksInList(listId: listId);
  }

  /// Permanently deletes `listId` and refreshes list collections.
  Future<void> deleteList(String listId) async {
    final bridge = ref.read(bridgeServiceProvider);
    await bridge.deleteList(listId: listId);
    ref.invalidateSelf();
    ref.invalidate(archivedListsProvider);
  }
}

final listsProvider = AsyncNotifierProvider<ListsNotifier, List<ListDto>>(
  ListsNotifier.new,
);

/// Manages archived lists shown in the collapsed archive section.
class ArchivedListsNotifier extends AsyncNotifier<List<ListDto>> {
  @override
  FutureOr<List<ListDto>> build() {
    return ref.watch(bridgeServiceProvider).getArchivedLists();
  }

  /// Restores `listId` and refreshes archived and active list collections.
  Future<void> unarchiveList(String listId) async {
    final bridge = ref.read(bridgeServiceProvider);
    await bridge.unarchiveList(listId: listId);
    ref.invalidateSelf();
    ref.invalidate(listsProvider);
  }
}

final archivedListsProvider =
    AsyncNotifierProvider<ArchivedListsNotifier, List<ListDto>>(
      ArchivedListsNotifier.new,
    );

/// Keeps the selected task display order in memory for the current app
/// session. Phase 1 intentionally does not persist this value to storage.
class TaskSortModeNotifier extends Notifier<TaskSortMode> {
  TaskSortModeNotifier(this.listId);

  final String listId;

  @override
  TaskSortMode build() {
    return TaskSortMode.manual;
  }

  void setMode(TaskSortMode mode) {
    state = mode;
  }
}

final taskSortModeProvider =
    NotifierProvider.family<TaskSortModeNotifier, TaskSortMode, String>(
      TaskSortModeNotifier.new,
    );

/// Manages the tasks of a single list, keyed by `listId`.
///
/// Invalidate strategy: [createTask], [updateTask], [setStatus] and [deleteTask] each
/// perform their bridge call first, then call `ref.invalidateSelf()`, which
/// re-runs [build] for this `listId` only (other lists' [TasksNotifier]
/// instances are untouched). [taskDetailProvider] derives its value from
/// this provider via `ref.watch`, so it is refreshed transitively whenever
/// this provider is invalidated -- no separate invalidate call is needed for
/// the detail screen.
class TasksNotifier extends AsyncNotifier<List<TaskDto>> {
  TasksNotifier(this.listId);

  final String listId;

  @override
  FutureOr<List<TaskDto>> build() {
    return ref.watch(bridgeServiceProvider).getTasks(listId: listId);
  }

  /// Creates a new task titled `title` in this list and refreshes the task
  /// list. When [parentTaskId] is provided, the new task is created as a
  /// subtask of that parent. The Rust/domain layer assigns the task sort order
  /// within the target sibling group.
  Future<void> createTask(String title, {String? parentTaskId}) async {
    final bridge = ref.read(bridgeServiceProvider);
    await bridge.createTask(
      listId: listId,
      title: title,
      parentTaskId: parentTaskId,
    );
    ref.invalidateSelf();
  }

  /// Updates editable task fields and refreshes the task list.
  Future<void> updateTask({
    required String taskId,
    required String title,
    required String note,
    required int priority,
    required int? dueAt,
  }) async {
    final bridge = ref.read(bridgeServiceProvider);
    await bridge.updateTask(
      taskId: taskId,
      title: title,
      note: note,
      priority: priority,
      dueAt: dueAt,
    );
    ref.invalidate(latestTaskUndoProvider);
    ref.invalidateSelf();
  }

  /// Transitions `taskId` to `status` and refreshes the task list.
  Future<void> setStatus(String taskId, String status) async {
    final bridge = ref.read(bridgeServiceProvider);
    await bridge.setTaskStatus(taskId: taskId, status: status);
    if (status == 'done') {
      ref.invalidate(latestTaskUndoProvider);
    }
    ref.invalidateSelf();
  }

  Future<int> countDescendants(String taskId) {
    return ref.read(bridgeServiceProvider).countTaskDescendants(taskId: taskId);
  }

  /// Permanently deletes `taskId` and its descendants, then refreshes the list.
  Future<void> deleteTask(String taskId) async {
    final bridge = ref.read(bridgeServiceProvider);
    await bridge.deleteTask(taskId: taskId);
    ref.invalidateSelf();
  }

  /// Moves `taskId` between sibling boundaries and refreshes the task list.
  Future<void> reorderTask({
    required String taskId,
    required String? previousTaskId,
    required String? nextTaskId,
  }) async {
    final bridge = ref.read(bridgeServiceProvider);
    await bridge.reorderTask(
      taskId: taskId,
      previousTaskId: previousTaskId,
      nextTaskId: nextTaskId,
    );
    ref.invalidateSelf();
  }
}

final tasksProvider =
    AsyncNotifierProvider.family<TasksNotifier, List<TaskDto>, String>(
      TasksNotifier.new,
    );

/// Identifies a single task for [taskDetailProvider]: the containing list id
/// plus the task id.
typedef TaskDetailArgs = ({String listId, String taskId});

/// Task detail lookup policy (M2-03): there is no dedicated "get task by
/// id" bridge API exposed yet, so the detail screen derives its data by
/// watching [tasksProvider] for the task's list and finding the matching
/// task client-side. This keeps a single cache/source of truth for tasks
/// (avoids a second, possibly stale, copy of task data) and avoids an extra
/// round trip to the bridge. If a dedicated get-task-by-id bridge call is
/// added later, this provider's body can be swapped to call it directly
/// without changing the screen that consumes it.
final taskDetailProvider =
    Provider.family<AsyncValue<TaskDto?>, TaskDetailArgs>((ref, args) {
      final tasksAsync = ref.watch(tasksProvider(args.listId));
      return tasksAsync.whenData((tasks) {
        for (final task in tasks) {
          if (task.id == args.taskId) {
            return task;
          }
        }
        return null;
      });
    });

/// Manages the latest task undo entry and applies undo through the bridge.
class LatestTaskUndoNotifier extends AsyncNotifier<TaskUndoDto?> {
  @override
  FutureOr<TaskUndoDto?> build() {
    return ref.watch(bridgeServiceProvider).getLatestTaskUndo();
  }

  Future<TaskDto> undo(String undoId) async {
    final restored = await ref
        .read(bridgeServiceProvider)
        .undoTaskOperation(undoId: undoId);
    ref.invalidate(tasksProvider(restored.listId));
    ref.invalidateSelf();
    await ref.read(tasksProvider(restored.listId).future);
    return restored;
  }
}

final latestTaskUndoProvider =
    AsyncNotifierProvider<LatestTaskUndoNotifier, TaskUndoDto?>(
      LatestTaskUndoNotifier.new,
    );
